name: RedEssentials
authors: [RedCraftPE, EventfulDeer48, ItsMax123]
version: 1.0.0
api: 3.0.0, 4.0.0
main: RedCraftPE\RedEssentials
commands:
  gmc:
    usage: /gmc [player]
    description: Give yourself or others creative mode!
  gms:
    usage: /gms [player]
    description: Give yourself or others survival mode!
  gma:
    usage: /gma [player]
    description: Give yourself or others adventure mode!
permissions:
  redessentials.*:
    default: op
    children:
      redessentials.gmc:
        default: op
        description: With this permission players will be able to give themselves creative mode.
      redessentials.gms:
        default: op
        description: With this permission players will be able to give themselves survival mode.
      redessentials.gma:
        default: op
        description: With this permission players will be able to give themselves adventure mode.
