name: RedEssentials
author: RedCraftPE
version: 1.0.0
api: 3.0.0, 4.0.0
main: RedCraftPE\RedEssentials
commands:
  gmc:
    usage: /gmc [player]
    description: Give yourself or others creative mode!
    permissions:
      redessentials.*:
        default: op
        children:
          redessentials.gmc:
            default: op
            description: With this permission players will be able to give themselves creative mode.
          redessentials.gms:
            default: op
            description: With this permission players will be able to give themselves survival mode.
          redessentials.gma:
            default: op
            description: With this permission players will be able to give themselves adventure mode.
