name: RedEssentials
authors: [RedCraftPE, EventfulDeer48, ItsMax123]
version: 1.0.0
api: 3.0.0, 4.0.0
main: RedCraftPE\RedEssentials
commands:
  gmc:
    usage: /gmc [player]
    description: Give yourself or others creative mode!
  gms:
    usage: /gms [player]
    description: Give yourself or others survival mode!
  gma:
    usage: /gma [player]
    description: Give yourself or others adventure mode!
  heal:
    usage: /heal [player]
    description: Heal yourself or other players!
  feed:
    usage: /feed [player]
    description: Feed yourself or other players!
    aliases: [food, eat]
  starve: 
    usage: /starve [player]
    description: Starve yourself or someone else!
  freeze:
    usage: /freeze <player>
    description: This command will freeze the target!
  unfreeze:
    usage: /unfreeze <player>
    description: This command will unfreeze the target!
  hunger:
    usage: /hunger <on/off>
    description: Enable/disable hunger on the server!
  svoid:
    usage: /svoid <on/off> [world]
    description: Enable/disable the void in an entire server or a specific world!
  repair:
    usage: /repair
    description: Repair the item in your hand, if repairable!
  vanish:
    usage: /vanish [player]
    description: Vanish! Become invisible, or make someone else invisible!
permissions:
  redessentials.*:
    default: op
    children:
      redessentials.gmc:
        default: op
        description: With this permission players will be able to give themselves creative mode.
      redessentials.gms:
        default: op
        description: With this permission players will be able to give themselves survival mode.
      redessentials.gma:
        default: op
        description: With this permission players will be able to give themselves adventure mode.
      redessentials.feed:
        default: op
        description: With this permission players will be able to feed themselves or others.
      redessentials.heal:
        default: op
        description: With this permission players will be able to heal themselves or others.
      redessentials.starve:
        default: op
        description: With this permission players will be able to starve themselves or others.
      redessentials.freeze:
        default: op
        description: With this permission players will be able to freeze others.
      redessentials.ufreeze:
        default: op
        description: With this permission players will be able to unfreeze others.
      redessentials.hunger:
        default: op
        description: With this permission players can enable/disable hunger on the server.
      redessentials.svoid:
        default: op
        description: With this permission players can enable/disable Safe Void in the entire server or in a specific world.
      redessentials.vanish:
        default: op
        description: With this permission players can make themselves, or others, invisible.
      redessentials.repair:
        default: op
        description: With this permission players can repair the tool in their hand.
